### PR TITLE
pyzstd_pep517: name config_settings argument correctly

### PR DESCRIPTION
**Pull request by gotmax23**
Ref: https://peps.python.org/pep-0517/#get-requires-for-build-wheel

### CODE REVIEW

**Comment by Rogdham** [comment]
Hello @gotmax23 and thank you for your patch!

I understand that the argument you changed is a positional or keyword parameter (e.g. `inspect.Parameter.POSITIONAL_OR_KEYWORD`), so having the wrong name breaks any build system that uses the parameter as a keyword parameter.

Could you tell a bit more about the context in which you are having an issue with this? For example, if your build system fails to build `pyzstd` as a result, please say which build system you are using and how you are calling it.

This will be helpful not only to reproduce, but also to give a proper importance level to this fix.

Thank you!

**Comment by gotmax23** [comment]
> Hello @gotmax23 and thank you for your patch!

Sure!

> Could you tell a bit more about the context in which you are having an issue with this? For example, if your build system fails to build pyzstd as a result, please say which build system you are using and how you are calling it.

I am using https://src.fedoraproject.org/rpms/pyproject-rpm-macros which is the build frontend tool we use for building python project RPMs for Fedora Linux (and Red Hat Enterprise Linux and CentOS and others). I am working on [importing pyzstd into the official Fedora repositories](https://bugzilla.redhat.com/show_bug.cgi?id=2273823).

**Comment by Rogdham** [comment]
Thank you for the explanations!

This will be shipped in next release (current target is by the end of May).

**Comment by Rogdham** [comment]
Fixed in version 0.16.0 that has just been released :rocket:

**Pull request merged**
